version: "3.4"

services:
  redis:
    image: redis
    ports:
      - "63799:6379"
    restart: always

  postgres:
    image: postgis/postgis:latest
    ports:
      - "54322:5432"
    restart: always
    volumes:
      - bad_weather_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "badweather"

volumes:
  bad_weather_db_volume:
